#############################################################################
# Makefile for building: build/lorem-ipsum.app/Contents/MacOS/lorem-ipsum
# Generated by qmake (3.1) (Qt 5.11.1)
# Project:  lorem-ipsum.pro
# Template: app
# Command: /usr/local/opt/qt/bin/qmake -o Makefile lorem-ipsum.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.11 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.11.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I/usr/local/Cellar/qt/5.11.1/mkspecs/macx-clang -F/usr/local/Cellar/qt/5.11.1/lib
QMAKE         = /usr/local/opt/qt/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/opt/qt/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/opt/qt/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = lorem-ipsum1.0.0
DISTDIR = /Users/joshgarde/Development/lorem-ipsum/out/lorem-ipsum1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.11 -Wl,-rpath,@executable_path/Frameworks
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt/5.11.1/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = out/

####### Files

SOURCES       = src/main.cpp \
		src/sections/sectionmodel.cpp \
		src/sections/chapter.cpp \
		src/sections/copyright.cpp \
		src/sections/tableofcontents.cpp \
		src/sections/title.cpp \
		src/renderer/bookrenderer.cpp \
		src/renderer/mainwindow.cpp \
		src/renderer/pagerenderer.cpp \
		src/renderer/addsectiondialog.cpp qrc_resources.cpp \
		moc_section.cpp \
		moc_addsectiondialog.cpp
OBJECTS       = out/main.o \
		out/sectionmodel.o \
		out/chapter.o \
		out/copyright.o \
		out/tableofcontents.o \
		out/title.o \
		out/bookrenderer.o \
		out/mainwindow.o \
		out/pagerenderer.o \
		out/addsectiondialog.o \
		out/qrc_resources.o \
		out/moc_section.o \
		out/moc_addsectiondialog.o
DIST          = /usr/local/Cellar/qt/5.11.1/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/lex.prf \
		lorem-ipsum.pro src/sections/section.h \
		src/sections/sectionmodel.h \
		src/sections/chapter.h \
		src/sections/copyright.h \
		src/sections/tableofcontents.h \
		src/sections/title.h \
		src/renderer/bookrenderer.h \
		src/renderer/mainwindow.h \
		src/renderer/pagerenderer.h \
		src/renderer/addsectiondialog.h src/main.cpp \
		src/sections/sectionmodel.cpp \
		src/sections/chapter.cpp \
		src/sections/copyright.cpp \
		src/sections/tableofcontents.cpp \
		src/sections/title.cpp \
		src/renderer/bookrenderer.cpp \
		src/renderer/mainwindow.cpp \
		src/renderer/pagerenderer.cpp \
		src/renderer/addsectiondialog.cpp
QMAKE_TARGET  = lorem-ipsum
DESTDIR       = build/
TARGET        = build/lorem-ipsum.app/Contents/MacOS/lorem-ipsum

####### Custom Variables
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d build/lorem-ipsum.app/Contents/MacOS/ || mkdir -p build/lorem-ipsum.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: lorem-ipsum.pro /usr/local/Cellar/qt/5.11.1/mkspecs/macx-clang/qmake.conf /usr/local/Cellar/qt/5.11.1/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/5.11.1/mkspecs/features/lex.prf \
		lorem-ipsum.pro \
		resources.qrc \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/QtWidgets.prl \
		/usr/local/Cellar/qt/5.11.1/lib/QtGui.framework/QtGui.prl \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile lorem-ipsum.pro
/usr/local/Cellar/qt/5.11.1/mkspecs/features/spec_pre.prf:
/usr/local/Cellar/qt/5.11.1/mkspecs/qdevice.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/features/device_config.prf:
/usr/local/Cellar/qt/5.11.1/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/5.11.1/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/5.11.1/mkspecs/common/macx.conf:
/usr/local/Cellar/qt/5.11.1/mkspecs/common/sanitize.conf:
/usr/local/Cellar/qt/5.11.1/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/5.11.1/mkspecs/common/gcc-base-mac.conf:
/usr/local/Cellar/qt/5.11.1/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/5.11.1/mkspecs/common/clang-mac.conf:
/usr/local/Cellar/qt/5.11.1/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3danimation.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_charts.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_core.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_gamepad.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_graphics_support_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_help.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_location.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_macextras.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_macextras_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_network.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_purchasing.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_repparser.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_script.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webengine.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webview.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_webview_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Cellar/qt/5.11.1/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/5.11.1/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/5.11.1/mkspecs/macx-clang/qmake.conf:
/usr/local/Cellar/qt/5.11.1/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/Cellar/qt/5.11.1/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/5.11.1/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/5.11.1/mkspecs/features/toolchain.prf:
/usr/local/Cellar/qt/5.11.1/mkspecs/features/mac/toolchain.prf:
/usr/local/Cellar/qt/5.11.1/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/5.11.1/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/5.11.1/mkspecs/features/resolve_config.prf:
/usr/local/Cellar/qt/5.11.1/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/5.11.1/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/5.11.1/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/5.11.1/mkspecs/features/mac/mac.prf:
/usr/local/Cellar/qt/5.11.1/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/5.11.1/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/5.11.1/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/5.11.1/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/5.11.1/mkspecs/features/unix/opengl.prf:
/usr/local/Cellar/qt/5.11.1/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/5.11.1/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/5.11.1/mkspecs/features/qmake_use.prf:
/usr/local/Cellar/qt/5.11.1/mkspecs/features/file_copies.prf:
/usr/local/Cellar/qt/5.11.1/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/5.11.1/mkspecs/features/mac/asset_catalogs.prf:
/usr/local/Cellar/qt/5.11.1/mkspecs/features/testcase_targets.prf:
/usr/local/Cellar/qt/5.11.1/mkspecs/features/exceptions.prf:
/usr/local/Cellar/qt/5.11.1/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/5.11.1/mkspecs/features/lex.prf:
lorem-ipsum.pro:
resources.qrc:
/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/QtWidgets.prl:
/usr/local/Cellar/qt/5.11.1/lib/QtGui.framework/QtGui.prl:
/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile lorem-ipsum.pro

qmake_all: FORCE

build/lorem-ipsum.app/Contents/PkgInfo: 
	@test -d build/lorem-ipsum.app/Contents || mkdir -p build/lorem-ipsum.app/Contents
	@$(DEL_FILE) build/lorem-ipsum.app/Contents/PkgInfo
	@echo "APPL????" > build/lorem-ipsum.app/Contents/PkgInfo
build/lorem-ipsum.app/Contents/Resources/empty.lproj: 
	@test -d build/lorem-ipsum.app/Contents/Resources || mkdir -p build/lorem-ipsum.app/Contents/Resources
	@touch build/lorem-ipsum.app/Contents/Resources/empty.lproj
	
build/lorem-ipsum.app/Contents/Info.plist: 
	@test -d build/lorem-ipsum.app/Contents || mkdir -p build/lorem-ipsum.app/Contents
	@$(DEL_FILE) build/lorem-ipsum.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.lorem-ipsum,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.lorem-ipsum,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.11,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,lorem-ipsum,g" -e "s,@LIBRARY@,lorem-ipsum,g" -e "s,\$${EXECUTABLE_NAME},lorem-ipsum,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /usr/local/Cellar/qt/5.11.1/mkspecs/macx-clang/Info.plist.app >build/lorem-ipsum.app/Contents/Info.plist

all: Makefile \
		build/lorem-ipsum.app/Contents/PkgInfo \
		build/lorem-ipsum.app/Contents/Resources/empty.lproj \
		build/lorem-ipsum.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/Cellar/qt/5.11.1/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/sections/section.h src/sections/sectionmodel.h src/sections/chapter.h src/sections/copyright.h src/sections/tableofcontents.h src/sections/title.h src/renderer/bookrenderer.h src/renderer/mainwindow.h src/renderer/pagerenderer.h src/renderer/addsectiondialog.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/sections/sectionmodel.cpp src/sections/chapter.cpp src/sections/copyright.cpp src/sections/tableofcontents.cpp src/sections/title.cpp src/renderer/bookrenderer.cpp src/renderer/mainwindow.cpp src/renderer/pagerenderer.cpp src/renderer/addsectiondialog.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r build/lorem-ipsum.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		/usr/local/Cellar/qt/5.11.1/bin/rcc \
		assets/add.png \
		assets/delete.png
	/usr/local/Cellar/qt/5.11.1/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/local/Cellar/qt/5.11.1/mkspecs/features/data/dummy.cpp
	/Library/Developer/CommandLineTools/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.11 -Wall -W -dM -E -o moc_predefs.h /usr/local/Cellar/qt/5.11.1/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_section.cpp moc_addsectiondialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_section.cpp moc_addsectiondialog.cpp
moc_section.cpp: /usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/QJsonObject \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/qjsonobject.h \
		src/sections/section.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.11.1/bin/moc
	/usr/local/Cellar/qt/5.11.1/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/local/Cellar/qt/5.11.1/mkspecs/macx-clang -I/Users/joshgarde/Development/lorem-ipsum -I/Users/joshgarde/Development/lorem-ipsum -I/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.11.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/9.0.0/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -F/usr/local/Cellar/qt/5.11.1/lib src/sections/section.h -o moc_section.cpp

moc_addsectiondialog.cpp: /usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/qdialog.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QListWidget \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/qlistwidget.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/qpushbutton.h \
		src/renderer/addsectiondialog.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.11.1/bin/moc
	/usr/local/Cellar/qt/5.11.1/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/local/Cellar/qt/5.11.1/mkspecs/macx-clang -I/Users/joshgarde/Development/lorem-ipsum -I/Users/joshgarde/Development/lorem-ipsum -I/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.11.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/9.0.0/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -F/usr/local/Cellar/qt/5.11.1/lib src/renderer/addsectiondialog.h -o moc_addsectiondialog.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

out/main.o: src/main.cpp /usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/qapplication.h \
		src/renderer/mainwindow.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QSplitter \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/qsplitter.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QListView \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/qlistview.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QToolBar \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/qtoolbar.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QStatusBar \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/qstatusbar.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QAction \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/qaction.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/QFile \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/qfile.h \
		src/renderer/bookrenderer.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QScrollArea \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/qscrollarea.h \
		src/sections/sectionmodel.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/QAbstractListModel \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		src/sections/section.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/QJsonObject \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/qjsonobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/main.o src/main.cpp

out/sectionmodel.o: src/sections/sectionmodel.cpp src/sections/sectionmodel.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/QAbstractListModel \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		src/sections/section.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/QJsonObject \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/qjsonobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/sectionmodel.o src/sections/sectionmodel.cpp

out/chapter.o: src/sections/chapter.cpp src/sections/chapter.h \
		src/sections/section.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/QJsonObject \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/qjsonobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/chapter.o src/sections/chapter.cpp

out/copyright.o: src/sections/copyright.cpp src/sections/copyright.h \
		src/sections/section.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/QJsonObject \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/qjsonobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/copyright.o src/sections/copyright.cpp

out/tableofcontents.o: src/sections/tableofcontents.cpp src/sections/tableofcontents.h \
		src/sections/section.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/QJsonObject \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/qjsonobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/tableofcontents.o src/sections/tableofcontents.cpp

out/title.o: src/sections/title.cpp src/sections/title.h \
		src/sections/section.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/QJsonObject \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/qjsonobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/title.o src/sections/title.cpp

out/bookrenderer.o: src/renderer/bookrenderer.cpp src/renderer/bookrenderer.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QScrollArea \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/qscrollarea.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/QDebug \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/qdebug.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtGui.framework/Headers/QPainter \
		/usr/local/Cellar/qt/5.11.1/lib/QtGui.framework/Headers/qpainter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/bookrenderer.o src/renderer/bookrenderer.cpp

out/mainwindow.o: src/renderer/mainwindow.cpp src/renderer/mainwindow.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QSplitter \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/qsplitter.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QListView \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/qlistview.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QToolBar \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/qtoolbar.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QStatusBar \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/qstatusbar.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QAction \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/qaction.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/QFile \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/qfile.h \
		src/renderer/bookrenderer.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QScrollArea \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/qscrollarea.h \
		src/sections/sectionmodel.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/QAbstractListModel \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		src/sections/section.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/QJsonObject \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/qjsonobject.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/QDebug \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/qdebug.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtGui.framework/Headers/QIcon \
		/usr/local/Cellar/qt/5.11.1/lib/QtGui.framework/Headers/qicon.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QFileDialog \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/qfiledialog.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QMenu \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/qmenu.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QListWidgetItem \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/qlistwidget.h \
		src/renderer/addsectiondialog.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/qdialog.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QListWidget \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/qpushbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/mainwindow.o src/renderer/mainwindow.cpp

out/pagerenderer.o: src/renderer/pagerenderer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/pagerenderer.o src/renderer/pagerenderer.cpp

out/addsectiondialog.o: src/renderer/addsectiondialog.cpp src/renderer/addsectiondialog.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/qdialog.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QListWidget \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/qlistwidget.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.11.1/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/QMetaObject \
		/usr/local/Cellar/qt/5.11.1/lib/QtCore.framework/Headers/qobjectdefs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/addsectiondialog.o src/renderer/addsectiondialog.cpp

out/qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/qrc_resources.o qrc_resources.cpp

out/moc_section.o: moc_section.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/moc_section.o moc_section.cpp

out/moc_addsectiondialog.o: moc_addsectiondialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/moc_addsectiondialog.o moc_addsectiondialog.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

